- name: Install and Configure 
  hosts: ansible_target2
  become: true
  vars:
    mysql_root_password: Passw.123
    tools:

  tasks:

  - name: Downlaod git repo 
    git:
      repo: https://github.com/Savaonu/mysql_webapp.git
      dest: /opt/academia/caca
      version: master

  - name: Create MySQL container
    shell: |
      docker run --detach --env MYSQL_ROOT_PASSWORD=dummypassword --env MYSQL_USER=todos-user --env MYSQL_PASSWORD=dummytodos --env MYSQL_DATABASE=todos --name mysql --publish 3306:3306 mysql:5.7


  - name: Create App container
    shell: |
      docker container run -p 8080:8080 --link=mysql -e RDS_HOSTNAME=mysql -d atingupta2005/todo-web-application-mysql:0.0.1-SNAPSHOT


  
  
  

