- name: Configure system
  hosts: all
  become: true
  tasks:

  ##### Update #####
    - name: Update to latest version
      yum:
        name: "*"
        state: latest
        exclude: kernel*

##### SELinux #####
    - name: Disable SELinux
      selinux:
        state: disabled

##### Firewall #####
    - name: Stop and Disable Firewalld
      service:
        name: firewalld
        state: stopped
        enabled: False

##### Hostname #####
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

##### Docker #####
    - name: Set mydistribution
      set_fact:
        mydistribution: "{{ 'centos' if (ansible_distribution == 'CentOS') else (ansible_distribution | lower) }}"
    - name: Add signing key
      rpm_key:
        key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
        state: present

    - name: Add repository into repo.d list
      yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: Start Docker
      service:
        name: docker
        enabled: true
        state: started




