- name: Create and configure ansbile user
  hosts: all
  
  tasks:
  - name: Create User
    user:
      name: ansible
      comment: Ansible user
      group: wheel
      generate_ssh_key: yes
      ssh_key_type: rsa
      ssh_key_file: .ssh/id_rsa
  - name: No passw in sudoers
    lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^# %wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
  - name: Copy authorized keys file 
    copy:
      src: /home/ansible/.ssh/authorized_keys
      dest: /home/ansible/.ssh/
      mode: 0600