- name: Create and configure ansbile user
  hosts: all
  
  tasks:
  - name: Create User
    user:
      name: ansible
      comment: Ansible user
      group: root
      generate_ssh_key: yes
      ssh_key_type: rsa
      ssh_key_file: .ssh/id_rsa
  - name: No passw in sudoers
    sudoers:
      user: ansible 
      nopassword: no 
      commands: ALL
  - name: Copy authorized keys file 
    copy:
      src: /home/ansibe/.ssh/authorized_keys
      dest: /home/ansibe/.ssh/authorized_keys
      mode: 0644